import type { TimetableEntry } from '../../../types/timetable';
import { CLASS_6A6_ID } from '../../students/constants/defaultClass6A6Students';

/**
 * Thời khóa biểu chuẩn chính khóa của Lớp 6A6 - Trường THCS Tân Hải
 * Năm học: 2026 - 2027
 */
export const DEFAULT_CLASS_6A6_TIMETABLE: TimetableEntry[] = [
  // ================= THỨ 2 (dayOfWeek = 2) =================
  {
    id: 'tkb-6a6-2-1',
    classId: CLASS_6A6_ID,
    dayOfWeek: 2,
    period: 1,
    periodDisplay: 1,
    session: 'morning',
    timeSlot: '07:00 - 07:45',
    subjectName: 'Chào cờ (SHDC)',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Sân trường',
    notes: 'Sinh hoạt dưới cờ toàn trường',
  },
  {
    id: 'tkb-6a6-2-2',
    classId: CLASS_6A6_ID,
    dayOfWeek: 2,
    period: 2,
    periodDisplay: 2,
    session: 'morning',
    timeSlot: '07:50 - 08:35',
    subjectName: 'Toán',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Hình học & Đo lường',
  },
  {
    id: 'tkb-6a6-2-3',
    classId: CLASS_6A6_ID,
    dayOfWeek: 2,
    period: 3,
    periodDisplay: 3,
    session: 'morning',
    timeSlot: '09:05 - 09:50',
    subjectName: 'Ngữ Văn',
    teacherName: 'Cô Trần Thị Lan',
    roomName: 'Phòng học 6A6',
    notes: 'Đọc hiểu văn bản',
  },
  {
    id: 'tkb-6a6-2-4',
    classId: CLASS_6A6_ID,
    dayOfWeek: 2,
    period: 4,
    periodDisplay: 4,
    session: 'morning',
    timeSlot: '09:55 - 10:40',
    subjectName: 'Ngữ Văn',
    teacherName: 'Cô Trần Thị Lan',
    roomName: 'Phòng học 6A6',
    notes: 'Thực hành Tiếng Việt',
  },
  {
    id: 'tkb-6a6-2-5',
    classId: CLASS_6A6_ID,
    dayOfWeek: 2,
    period: 5,
    periodDisplay: 5,
    session: 'morning',
    timeSlot: '10:45 - 11:30',
    subjectName: 'GDTC (Thể dục)',
    teacherName: 'Thầy Nguyễn Văn Nam',
    roomName: 'Khu thể chất',
    notes: 'Đội hình đội ngũ',
  },

  // ================= THỨ 3 (dayOfWeek = 3) =================
  {
    id: 'tkb-6a6-3-1',
    classId: CLASS_6A6_ID,
    dayOfWeek: 3,
    period: 1,
    periodDisplay: 1,
    session: 'morning',
    timeSlot: '07:00 - 07:45',
    subjectName: 'KHTN (Khoa học tự nhiên)',
    teacherName: 'Cô Đặng Thúy Nga',
    roomName: 'Phòng học 6A6',
    notes: 'Vật lý & Hóa học đại cương',
  },
  {
    id: 'tkb-6a6-3-2',
    classId: CLASS_6A6_ID,
    dayOfWeek: 3,
    period: 2,
    periodDisplay: 2,
    session: 'morning',
    timeSlot: '07:50 - 08:35',
    subjectName: 'KHTN (Khoa học tự nhiên)',
    teacherName: 'Cô Đặng Thúy Nga',
    roomName: 'Phòng học 6A6',
    notes: 'Thí nghiệm thực hành',
  },
  {
    id: 'tkb-6a6-3-3',
    classId: CLASS_6A6_ID,
    dayOfWeek: 3,
    period: 3,
    periodDisplay: 3,
    session: 'morning',
    timeSlot: '09:05 - 09:50',
    subjectName: 'Tiếng Anh',
    teacherName: 'Cô Mai Phương Thảo',
    roomName: 'Phòng học 6A6',
    notes: 'Unit 1: My New School',
  },
  {
    id: 'tkb-6a6-3-4',
    classId: CLASS_6A6_ID,
    dayOfWeek: 3,
    period: 4,
    periodDisplay: 4,
    session: 'morning',
    timeSlot: '09:55 - 10:40',
    subjectName: 'Lịch sử & Địa lý',
    teacherName: 'Thầy Hoàng Quốc Việt',
    roomName: 'Phòng học 6A6',
    notes: 'Phần Lịch sử thế giới cổ đại',
  },
  {
    id: 'tkb-6a6-3-5',
    classId: CLASS_6A6_ID,
    dayOfWeek: 3,
    period: 5,
    periodDisplay: 5,
    session: 'morning',
    timeSlot: '10:45 - 11:30',
    subjectName: 'GDCD',
    teacherName: 'Cô Lê Thu Trang',
    roomName: 'Phòng học 6A6',
    notes: 'Bài 1: Tự hào về truyền thống',
  },

  // ================= THỨ 4 (dayOfWeek = 4) =================
  {
    id: 'tkb-6a6-4-1',
    classId: CLASS_6A6_ID,
    dayOfWeek: 4,
    period: 1,
    periodDisplay: 1,
    session: 'morning',
    timeSlot: '07:00 - 07:45',
    subjectName: 'Toán',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Số học & Phép tính',
  },
  {
    id: 'tkb-6a6-4-2',
    classId: CLASS_6A6_ID,
    dayOfWeek: 4,
    period: 2,
    periodDisplay: 2,
    session: 'morning',
    timeSlot: '07:50 - 08:35',
    subjectName: 'Toán',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Luyện tập phương trình',
  },
  {
    id: 'tkb-6a6-4-3',
    classId: CLASS_6A6_ID,
    dayOfWeek: 4,
    period: 3,
    periodDisplay: 3,
    session: 'morning',
    timeSlot: '09:05 - 09:50',
    subjectName: 'Tin học',
    teacherName: 'Thầy Bùi Quang Huy',
    roomName: 'Phòng máy tính 1',
    notes: 'Thực hành máy vi tính',
  },
  {
    id: 'tkb-6a6-4-4',
    classId: CLASS_6A6_ID,
    dayOfWeek: 4,
    period: 4,
    periodDisplay: 4,
    session: 'morning',
    timeSlot: '09:55 - 10:40',
    subjectName: 'Tiếng Anh',
    teacherName: 'Cô Mai Phương Thảo',
    roomName: 'Phòng học 6A6',
    notes: 'Luyện kỹ năng Nghe - Nói',
  },
  {
    id: 'tkb-6a6-4-5',
    classId: CLASS_6A6_ID,
    dayOfWeek: 4,
    period: 5,
    periodDisplay: 5,
    session: 'morning',
    timeSlot: '10:45 - 11:30',
    subjectName: 'Công nghệ',
    teacherName: 'Cô Vũ Bích Ngọc',
    roomName: 'Phòng học 6A6',
    notes: 'Công nghệ đời sống',
  },

  // ================= THỨ 5 (dayOfWeek = 5) =================
  {
    id: 'tkb-6a6-5-1',
    classId: CLASS_6A6_ID,
    dayOfWeek: 5,
    period: 1,
    periodDisplay: 1,
    session: 'morning',
    timeSlot: '07:00 - 07:45',
    subjectName: 'Ngữ Văn',
    teacherName: 'Cô Trần Thị Lan',
    roomName: 'Phòng học 6A6',
    notes: 'Viết đoạn văn biểu cảm',
  },
  {
    id: 'tkb-6a6-5-2',
    classId: CLASS_6A6_ID,
    dayOfWeek: 5,
    period: 2,
    periodDisplay: 2,
    session: 'morning',
    timeSlot: '07:50 - 08:35',
    subjectName: 'Ngữ Văn',
    teacherName: 'Cô Trần Thị Lan',
    roomName: 'Phòng học 6A6',
    notes: 'Nói và nghe',
  },
  {
    id: 'tkb-6a6-5-3',
    classId: CLASS_6A6_ID,
    dayOfWeek: 5,
    period: 3,
    periodDisplay: 3,
    session: 'morning',
    timeSlot: '09:05 - 09:50',
    subjectName: 'KHTN (Khoa học tự nhiên)',
    teacherName: 'Cô Đặng Thúy Nga',
    roomName: 'Phòng học 6A6',
    notes: 'Sinh học tế bào',
  },
  {
    id: 'tkb-6a6-5-4',
    classId: CLASS_6A6_ID,
    dayOfWeek: 5,
    period: 4,
    periodDisplay: 4,
    session: 'morning',
    timeSlot: '09:55 - 10:40',
    subjectName: 'KHTN (Khoa học tự nhiên)',
    teacherName: 'Cô Đặng Thúy Nga',
    roomName: 'Phòng học 6A6',
    notes: 'Thực hành quan sát hiển vi',
  },
  {
    id: 'tkb-6a6-5-5',
    classId: CLASS_6A6_ID,
    dayOfWeek: 5,
    period: 5,
    periodDisplay: 5,
    session: 'morning',
    timeSlot: '10:45 - 11:30',
    subjectName: 'Nghệ thuật (Âm nhạc)',
    teacherName: 'Thầy Nguyễn Hoàng Long',
    roomName: 'Phòng âm nhạc',
    notes: 'Học hát bài mới',
  },

  // ================= THỨ 6 (dayOfWeek = 6) =================
  {
    id: 'tkb-6a6-6-1',
    classId: CLASS_6A6_ID,
    dayOfWeek: 6,
    period: 1,
    periodDisplay: 1,
    session: 'morning',
    timeSlot: '07:00 - 07:45',
    subjectName: 'Tiếng Anh',
    teacherName: 'Cô Mai Phương Thảo',
    roomName: 'Phòng học 6A6',
    notes: 'Grammar review & vocabulary',
  },
  {
    id: 'tkb-6a6-6-2',
    classId: CLASS_6A6_ID,
    dayOfWeek: 6,
    period: 2,
    periodDisplay: 2,
    session: 'morning',
    timeSlot: '07:50 - 08:35',
    subjectName: 'Toán',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Ôn tập chương 1',
  },
  {
    id: 'tkb-6a6-6-3',
    classId: CLASS_6A6_ID,
    dayOfWeek: 6,
    period: 3,
    periodDisplay: 3,
    session: 'morning',
    timeSlot: '09:05 - 09:50',
    subjectName: 'Lịch sử & Địa lý',
    teacherName: 'Thầy Hoàng Quốc Việt',
    roomName: 'Phòng học 6A6',
    notes: 'Phần Địa lý tự nhiên',
  },
  {
    id: 'tkb-6a6-6-4',
    classId: CLASS_6A6_ID,
    dayOfWeek: 6,
    period: 4,
    periodDisplay: 4,
    session: 'morning',
    timeSlot: '09:55 - 10:40',
    subjectName: 'HĐTN, HN',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Hoạt động hướng nghiệp & trải nghiệm',
  },
  {
    id: 'tkb-6a6-6-5',
    classId: CLASS_6A6_ID,
    dayOfWeek: 6,
    period: 5,
    periodDisplay: 5,
    session: 'morning',
    timeSlot: '10:45 - 11:30',
    subjectName: 'Sinh hoạt lớp (SHL)',
    teacherName: 'Thầy Phan Văn Bộ',
    roomName: 'Phòng học 6A6',
    notes: 'Tổng kết thi đua tuần & Kế hoạch tuần tới',
  },
];
